import { NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

const GEMINI_API_KEY = "AIzaSyCoaNv8rp-UVQ3uqio5VD9dIAZQsPR5ok4";

export async function POST(request) {
  if (!GEMINI_API_KEY) {
    console.error('💥 Missing GEMINI_API_KEY environment variable.');
    return NextResponse.json(
      { error: 'Server configuration error: Missing API key.' },
      { status: 500 }
    );
  }

  try {
    const { topic, customQuestions, uploadedStories, length, language, hostName, artistName, autoGenerated } = await request.json();

    console.log('🔍 Request received with data:', {
      topic,
      length,
      language,
      hostName,
      artistName,
      autoGenerated,
      customQuestionsCount: customQuestions?.length || 0,
      uploadedStoriesCount: uploadedStories?.length || 0
    });

    // Build your prompt
    let durationGuide = '';
    if (length === 'short') durationGuide = '3-5 minutes';
    else if (length === 'medium') durationGuide = '8-12 minutes';
    else durationGuide = '15-20 minutes';

    let customQuestionsText = '';
    if (customQuestions && customQuestions.length > 0) {
      customQuestionsText = `\n\nThe host should ask these specific questions during the interview:\n${customQuestions.map((q, i) => `${i + 1}. ${q}`).join('\n')}`;
    }

    let storiesContext = '';
    if (uploadedStories && uploadedStories.length > 0) {
      storiesContext = `\n\nThe artist has shared these stories that should be incorporated naturally into the podcast:\n${uploadedStories.join('\n\n')}`;
    }

    const prompt = 'You are a podcast script writer. Create a ' + length + ' podcast script (approximately ' + durationGuide + ') in ' + language + ' language about "' + topic + '".\n\n' +
    'Host name: ' + hostName + '\n' +
    'Artist/Guest name: ' + artistName + customQuestionsText + storiesContext + '\n\n' +
    'IMPORTANT FORMAT INSTRUCTIONS:\n' +
    '- Write the script as a natural conversation between ' + hostName + ' and ' + artistName + '\n' +
    '- Format each line as: "SpeakerName: What they say"\n' +
    '- Use EXACTLY these names: ' + hostName + ' and ' + artistName + '\n' +
    '- Include natural back-and-forth dialogue\n' +
    '- Have a warm, conversational tone appropriate for Indian audience\n' +
    '- Include smooth transitions between topics\n\n' +
    'Example format:\n' +
    hostName + ': Welcome to the show! Today we are talking about ' + topic + '.\n' +
    artistName + ': Thank you for having me! I am excited to discuss this.\n' +
    hostName + ': So tell me, what inspired you?\n\n' +
    'Return ONLY the dialogue in this format. NO JSON, NO markdown, NO code blocks. Just the conversation with "Name: dialogue" format.';


    console.log('🚀 Making API call to Google Gemini with model: gemini-2.0-flash-exp');

    const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
    const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash-exp" });

    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();

    console.log('✅ Gemini response received');

    let scriptText = text.trim();

    // Remove markdown code blocks if present (just in case the model ignored the instruction)
    if (scriptText.startsWith('```')) {
      // Remove the opening fence (e.g., ```json\n or ```\n)
      scriptText = scriptText.replace(/^```[a-z]*\n?/i, '');
      // Remove the closing fence (e.g., \n```)
      if (scriptText.endsWith('```')) {
        scriptText = scriptText.slice(0, -3).trim();
      }
    }

    console.log('📝 Script generated successfully');

    // Return the plain text script directly - no JSON parsing needed!
    return NextResponse.json({
      script: scriptText,
      title: topic,
      hostName: hostName,
      artistName: artistName
    });

  } catch (error) {
    console.error('❌ Error generating podcast script:', error);
    return NextResponse.json(
      { error: 'Failed to generate podcast script', details: error.message },
      { status: 500 }
    );
  }
}
