import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';

// Hardcoded API key - NOT RECOMMENDED for production
const API_KEY = 'AIzaSyCoaNv8rp-UVQ3uqio5VD9dIAZQsPR5ok4';
const MODEL_NAME = 'gemini-2.5-flash-image-preview';

export async function POST(request: NextRequest) {
  try {
    const { prompt, imageBase64 } = await request.json();

    if (!prompt || !imageBase64) {
      return NextResponse.json(
        { error: 'Missing prompt or image' },
        { status: 400 }
      );
    }

    // Initialize the Gemini client
    const genAI = new GoogleGenerativeAI(API_KEY);
    const model = genAI.getGenerativeModel({ model: MODEL_NAME });

    // Convert base64 to the format Gemini expects
    const imageParts = {
      inlineData: {
        data: imageBase64.split(',')[1] || imageBase64,
        mimeType: 'image/png'
      }
    };

    // Generate content with image + prompt
    const result = await model.generateContent([prompt, imageParts]);
    const response = result.response;

    // Extract generated image from response
    let generatedImageData = null;
    let textResponse = '';

    if (response.candidates && response.candidates.length > 0) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          generatedImageData = part.inlineData;
        } else if (part.text) {
          textResponse = part.text;
        }
      }
    }

    if (generatedImageData && generatedImageData.mimeType.startsWith('image/')) {
      // Convert to base64 string for frontend
      const imageBase64Result = `data:${generatedImageData.mimeType};base64,${generatedImageData.data}`;
      
      return NextResponse.json({
        success: true,
        generatedImage: imageBase64Result,
        textResponse: textResponse
      });
    } else {
      return NextResponse.json(
        { error: 'No image generated by model' },
        { status: 500 }
      );
    }

  } catch (error: unknown) {
    console.error('Gemini API Error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to generate image';
    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    );
  }
}
