import { NextRequest, NextResponse } from 'next/server';
// 1. Import the 'Part' type
import { GoogleGenerativeAI, Part } from '@google/generative-ai';

// API key from environment variable
const API_KEY = process.env.api_generate_image; // This is now 'string | undefined'
const MODEL_NAME = 'gemini-2.5-flash-image-preview';

export async function POST(request: NextRequest) {
  try {
    const { prompt, imageBase64, customApiKey } = await request.json();

    // Use custom API key if provided, otherwise use environment variable
    const apiKey = customApiKey || API_KEY;

    if (!apiKey) {
      return NextResponse.json(
        { error: 'API key is not configured. Please provide a custom API key.' },
        { status: 500 }
      );
    }

    if (!prompt) {
      return NextResponse.json(
        { error: 'Missing prompt' },
        { status: 400 }
      );
    }

    // Initialize the Gemini client
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: MODEL_NAME });

    // 2. Change 'any[]' to 'Part[]' and wrap the prompt
    const contentParts: Part[] = [{ text: prompt }];

    if (imageBase64) {
      // If image is provided, add it for image-to-image generation
      // 3. Explicitly type the image part
      const imagePart: Part = {
        inlineData: {
          data: imageBase64.split(',')[1] || imageBase64,
          mimeType: 'image/png'
        }
      };
      contentParts.push(imagePart);
    }

    // Generate content
    const result = await model.generateContent(contentParts);
    const response = result.response;

    // Extract generated image from response
    let generatedImageData = null;
    let textResponse = '';

    if (response.candidates && response.candidates.length > 0) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          generatedImageData = part.inlineData;
        } else if (part.text) {
          textResponse = part.text;
        }
      }
    }

    if (generatedImageData && generatedImageData.mimeType.startsWith('image/')) {
      // Convert to base64 string for frontend
      const imageBase64Result = `data:${generatedImageData.mimeType};base64,${generatedImageData.data}`;

      return NextResponse.json({
        success: true,
        generatedImage: imageBase64Result,
        textResponse: textResponse
      });
    } else {
      return NextResponse.json(
        { error: 'No image generated by model' },
        { status: 500 }
      );
    }

  } catch (error: unknown) {
    console.error('Gemini API Error:', error);
    const errorMessage = error instanceof Error ? error.message : 'Failed to generate image';
    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    );
  }
}